/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;
import static ferramentas.Conexao.*;
import ferramentas.JTabela;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
/**
 *
 * @author AndersonCS
 */
public class Caixa extends javax.swing.JFrame {
    private final int COMANDA = 1, CLIENTE = 2;
    private Date data;
    private int tipo, idCli = 0, idPro = 0;
    
    /**
     * Creates new form Caixa
     */
    public Caixa() {
        initComponents();
        preencherJTabela("");
        data = new Date();
        Calendar d = Calendar.getInstance();
        int e = d.get(Calendar.MONTH) + 1;
        lblData.setText("Jandira "+d.get(Calendar.DATE)+" / "+e+" / "+d.get(Calendar.YEAR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblData = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        btnGravarCompra = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnEncerrar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btPesquisarPro = new javax.swing.JButton();
        lblDebitos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblData.setText("Jandira 24/03/2016");

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Mcoffe");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cliente");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Debitos R$");

        txtCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Codigo do produto");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Descrição do produto");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Valor R$");

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtDescricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDescricao.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtValor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnGravarCompra.setText("Gravar compra");
        btnGravarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarCompraActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar Pedidio");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnEncerrar.setText("Voltar");
        btnEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncerrarActionPerformed(evt);
            }
        });

        btnPesquisar.setText("pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btPesquisarPro.setText("pesquisar");
        btPesquisarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarProActionPerformed(evt);
            }
        });

        lblDebitos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTabela.setColumnSelectionAllowed(true);
        jTabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTabela);
        jTabela.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisar)
                                .addGap(53, 53, 53))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblDebitos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btPesquisarPro)
                                .addGap(18, 18, 18)
                                .addComponent(btnGravarCompra)
                                .addGap(18, 18, 18)
                                .addComponent(btnFechar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEncerrar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDebitos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravarCompra)
                    .addComponent(btnFechar)
                    .addComponent(btnEncerrar)
                    .addComponent(btPesquisarPro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        if(txtCliente.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Preencha cliente!");     
        }else{
            idCli = 0;
            try{
                if(txtCliente.getText().matches("[0-9]{1,3}")){
                    cr = cs.executeQuery("select * from comanda where num like '%"+txtCliente.getText()+"%';");
                    if(cr.first()){
                        txtCliente.setText(cr.getString("num"));
                        lblDebitos.setText("R$ "+cr.getString("lpre"));
                        tipo = COMANDA;
                        idCli = cr.getInt("id");
                        preencherJTabela("SELECT * FROM venCom where idCom = '"+idCli+"';");
                    }else{
                        idCli = 0;
                    }
                }else{
                    cr = cs.executeQuery("select * from cliente where nome like '%"+txtCliente.getText()+"%';");
                    if(cr.first()){
                        txtCliente.setText(cr.getString("nome"));
                        lblDebitos.setText("R$ "+cr.getString("cpre"));
                        tipo = CLIENTE;
                        idCli = cr.getInt("id");
                        preencherJTabela("SELECT * FROM venCli where idCli = '"+idCli+"';");
                    }else{
                        idCli = 0;
                    }
                }
            }catch(Exception e){}
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        new Pagamento().setVisible(true);
        Caixa.this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnGravarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarCompraActionPerformed
        // TODO add your handling code here:
        if(idCli == 0){
            JOptionPane.showMessageDialog(rootPane, "Cliente não selecionado!");
        }else{
            if(!(txtValor.getText().matches("([0-9]*)([.]?)([0-9]{0,2})"))){
                JOptionPane.showMessageDialog(rootPane, "Valor invalido!");
            }else{
                try{
                    float pre = 0;
                    if(idPro != 0){
                        cr = cs.executeQuery("select * from estoque where cod like "+idPro+";");
                        if(cr.first()){                            
                            if(cr.getInt("qua") <= 0){
                                JOptionPane.showMessageDialog(rootPane, "Produto esgotado!");
                                pre = 0;
                            }else{                              
                                pre = cr.getFloat("pre");
                                cs.executeUpdate("update estoque set qua = qua - 1 where cod = "+idPro+";");                                
                            }
                        }else{
                            JOptionPane.showMessageDialog(rootPane, "Erro ao gravar!");
                            pre = 0;
                        }
                    }else if(!(txtValor.getText().isEmpty())){
                        pre = Float.parseFloat(txtValor.getText());
                        idPro = 0;
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Preencha aumenos valor!");
                        pre = 0;
                    }
                    if(pre != 0){
                        String cli = "";
                        if(tipo == CLIENTE){
                            cs.executeUpdate("update cliente set cpre = cpre + "+pre+" WHERE id = "+idCli+";");
                            cr = cs.executeQuery("select * from cliente where id = "+idCli+";");
                            if(cr.first()){
                                lblDebitos.setText(cr.getString("cpre"));
                            }
                            cli = "Cli";
                        }else if(tipo == COMANDA){
                            cs.executeUpdate("update comanda set lpre = lpre + "+pre+" WHERE id = "+idCli+";");
                            cr = cs.executeQuery("select * from comanda where id = "+idCli+";");
                            if(cr.first()){
                                lblDebitos.setText(cr.getString("lpre"));
                            }
                            cli = "Com";
                        }
                        if(!cli.isEmpty()){
                            if(idPro != 0){
                                cs.executeUpdate("insert into venda (codPro, id"+cli+", dat, pre) values ('"+idPro+"', '"+idCli+"', '"+String.format("%tF", data)+"', '"+pre+"');");
                            }else{
                                cs.executeUpdate("insert into venda (id"+cli+", dat, pre) values ('"+idCli+"', '"+String.format("%tF", data)+"', '"+pre+"');");
                            }                            
                            preencherJTabela("SELECT * FROM ven"+cli+" where id"+cli+" = '"+idCli+"';");
                        }                                           
                    }
                }catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane, "Erro ao gravar!"+e);
                    idPro = 0;
                }
            }
        }
    }//GEN-LAST:event_btnGravarCompraActionPerformed

    private void btPesquisarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarProActionPerformed
        // TODO add your handling code here:        
        if(!(txtCodigo.getText().matches("[0-9]+")) && txtDescricao.getText().isEmpty()){
            txtCodigo.setText("");
            txtDescricao.setText("");
            txtValor.setText("");
            JOptionPane.showMessageDialog(rootPane, "Preencha corretamente os campos: Codigo ou Descrição!");
        }else{
            try{
                if(txtCodigo.getText().matches("[0-9]+")){
                    cr = cs.executeQuery("select * from estoque where cod like '"+txtCodigo.getText()+"';");
                    if(!cr.first()){
                        JOptionPane.showMessageDialog(rootPane, "Codigo não encontado!");
                    }
                }else{
                    cr = cs.executeQuery("select * from estoque where pro like '%"+txtDescricao.getText()+"%';");
                    if(!cr.first()){
                        JOptionPane.showMessageDialog(rootPane, "Produto não encontado!");
                    }
                }
                if(cr.first()){
                    txtCodigo.setText(cr.getString("cod"));
                    txtDescricao.setText(cr.getString("pro"));
                    txtValor.setText(cr.getString("pre"));
                    idPro = cr.getInt("cod");
                }else{
                    txtCodigo.setText("");
                    txtDescricao.setText("");
                    txtValor.setText("");
                    idPro = 0;
                }
            }catch(Exception e){}
        }
    }//GEN-LAST:event_btPesquisarProActionPerformed

    private void btnEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncerrarActionPerformed
        // TODO add your handling code here:
        PaginaInicial.pagInc.setVisible(true);
        Caixa.this.dispose();
    }//GEN-LAST:event_btnEncerrarActionPerformed

    public void preencherJTabela(String SQL){
        //
        ArrayList dados = new ArrayList();
        System.out.println(SQL);
        
        String colunas[] = new String[]{"Descrição do produto","Data da compra","Preço"};   
        if(!SQL.isEmpty()){
            try{
                cr = cs.executeQuery(SQL);
                if(cr.first()){
                    do{
                       dados.add(new Object[]{cr.getString("pro"),cr.getString("dat"),cr.getFloat("pre")});               
                    }while(cr.next());   
                }
            }catch(Exception e){
                System.out.println(e);
            }
        }
        JTabela tabela = new JTabela(dados, colunas);
        jTabela.setModel(tabela);
        jTabela.getColumnModel().getColumn(0).setPreferredWidth(210);
        jTabela.getColumnModel().getColumn(0).setResizable(false);
        jTabela.getColumnModel().getColumn(1).setPreferredWidth(128);
        jTabela.getColumnModel().getColumn(1).setResizable(false);
        jTabela.getColumnModel().getColumn(2).setPreferredWidth(59);
        jTabela.getColumnModel().getColumn(2).setResizable(false);
        jTabela.getTableHeader().setReorderingAllowed(false);
        jTabela.setAutoResizeMode(jTabela.AUTO_RESIZE_OFF);
        jTabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //*/
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisarPro;
    private javax.swing.JButton btnEncerrar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGravarCompra;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabela;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDebitos;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
