/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import static ferramentas.Conexao.*;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author AndersonCS
 */
public class Estoque extends javax.swing.JFrame {
    private int cod = 0;
    /** Creates new form Estoque */
    public Estoque() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPro = new javax.swing.JTextField();
        lbl = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        txtQua = new javax.swing.JTextField();
        lbl2 = new javax.swing.JLabel();
        txtPre = new javax.swing.JTextField();
        lbl4 = new javax.swing.JLabel();
        txtQum = new javax.swing.JTextField();
        txtPmp = new javax.swing.JTextField();
        lbl5 = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnApagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl.setText("Descrição do Produto");

        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Quantidade em Estoque");

        txtQua.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("Preço de Venda");

        txtPre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl4.setText("Preço da matéria Prima");

        txtQum.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPmp.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl5.setText("Quantidade Miníma");

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setText("Código do produto");

        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnApagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl2)
                            .addComponent(txtPre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl1)
                            .addComponent(txtQua, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl)
                            .addComponent(txtPro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQum, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl4)
                            .addComponent(txtPmp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPmp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl5)
                        .addGap(18, 18, 18)
                        .addComponent(txtQum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl2)
                                .addGap(18, 18, 18)
                                .addComponent(txtPre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl1)
                                .addGap(18, 18, 18)
                                .addComponent(txtQua, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnGravar)
                    .addComponent(btnVoltar)
                    .addComponent(btnApagar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        PaginaInicial.pagInc.setVisible(true);
        Estoque.this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        // TODO add your handling code here:
        if(!(txtPmp.getText().matches("([0-9]*)([.]?)([0-9]{0,2})")&&txtPre.getText().matches("([0-9]*)([.]?)([0-9]{0,2})")
                &&txtQua.getText().matches("[0-9]+")&&txtQum.getText().matches("[0-9]+"))||txtPro.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos corretamente!");
        }else{
            if(JOptionPane.showConfirmDialog(rootPane, "Gravar produto?") == 0){
                try{
                    cr = cs.executeQuery("select * from estoque where pro like '"+txtPro.getText()+"';");
                    if(cr.first()){
                        JOptionPane.showMessageDialog(rootPane, "Já existe!");
                    }else{
                        String sql = "insert into estoque (pro,pmp,pre,qua,qum) values ('%s','%s','%s','%s','%s');";
                        cs.executeUpdate(String.format(sql, txtPro.getText(), txtPmp.getText(), txtPre.getText(), txtQua.getText(), txtQum.getText()));
                        JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!");
                    }
                }catch(Exception e){JOptionPane.showMessageDialog(rootPane, "Erro ao gravar!");}
            }
        }//*/
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        txtPmp.setText("");
        txtPre.setText("");
        txtQua.setText("");
        txtQum.setText("");
        cod = 0;
        if(txtCodigo.getText().isEmpty() && txtPro.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Preencha os campos: Codigo ou Descrição!");
        }else{
            try{
                if(!txtCodigo.getText().isEmpty()){
                    cr = cs.executeQuery("select * from estoque where cod like '%"+txtCodigo.getText()+"%';");
                    if(!cr.first()){
                        txtCodigo.setText("");
                        txtPro.setText("");
                        cod = 0;
                        JOptionPane.showMessageDialog(rootPane, "Código do produto\nnão encontrado!");
                    }
                }else{
                    cr = cs.executeQuery("select * from estoque where pro like '%"+txtPro.getText()+"%';");
                    if(!cr.first()){
                        txtPro.setText("");
                        txtCodigo.setText("");
                        cod = 0;
                        JOptionPane.showMessageDialog(rootPane, "Nome do produto\nnão encontrado!");
                    }
                }
                if(cr.first()){
                    txtCodigo.setText(cr.getString("cod"));
                    txtPro.setText(cr.getString("pro"));
                    txtPmp.setText(cr.getString("pmp"));
                    txtPre.setText(cr.getString("pre"));
                    txtQua.setText(cr.getString("qua"));
                    txtQum.setText(cr.getString("qum"));
                    cod = cr.getInt("cod");
                }
            }catch(Exception e){}
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        if(!(txtPmp.getText().matches("([0-9]*)([.]?)([0-9]{0,2})")&&txtPre.getText().matches("([0-9]*)([.]?)([0-9]{0,2})")
                &&txtQua.getText().matches("[0-9]+")&&txtQum.getText().matches("[0-9]+"))
                ||txtPro.getText().isEmpty()||txtCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos corretamente!");
        }else{
            if(JOptionPane.showConfirmDialog(rootPane, "Atualizar produto?") == 0){
                try{
                    if(cod != 0){
                        cs.executeUpdate("update estoque set pmp = '"+txtPmp.getText()+"', pre = '"+txtPre.getText()+"', qua = '"+txtQua.getText()+"', qum = '"+txtQum.getText()+"' where cod = '"+cod+"';");
                        JOptionPane.showMessageDialog(rootPane, "Atualizado com sucesso!");
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Erro ao atualizar!");
                    }
                }catch(Exception e){JOptionPane.showMessageDialog(rootPane, "Erro ao atualizar!");}
            }
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(rootPane, "Apagar produto?") == 0){
            try{
                if(cod != 0){
                    cs.executeUpdate("delete from mcoffe.estoque where cod = "+cod+";");
                    txtCodigo.setText("");
                    txtPmp.setText("");
                    txtPre.setText("");
                    txtPro.setText("");
                    txtQua.setText("");
                    txtQum.setText("");
                    cod = 0;
                    JOptionPane.showMessageDialog(rootPane, "Deletado com sucesso!");
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Erro ao deletar!");
                }
            }catch(Exception e){JOptionPane.showMessageDialog(rootPane, "Erro ao deletar!");}
        }
    }//GEN-LAST:event_btnApagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtPmp;
    private javax.swing.JTextField txtPre;
    private javax.swing.JTextField txtPro;
    private javax.swing.JTextField txtQua;
    private javax.swing.JTextField txtQum;
    // End of variables declaration//GEN-END:variables

}
