/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import static ferramentas.Conexao.*;
import ferramentas.JTabela;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author AndersonCS
 */
public class Pagamento extends javax.swing.JFrame {
    private static final int COMANDA = 1, CLIENTE = 2;
    private int tipo, id = 0;
    private ResultSet cr;
    /**
     * Creates new form Pagamento
     */
    public Pagamento() {
        initComponents();
        preencherJTabela("");
        Calendar d = Calendar.getInstance();
        int e = d.get(Calendar.MONTH) + 1;
        lblData.setText("Jandira "+d.get(Calendar.DATE)+" / "+e+" / "+d.get(Calendar.YEAR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtClientePag = new javax.swing.JTextField();
        lblTroco = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabelaPag = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        btnCalcularPag = new javax.swing.JButton();
        btnImprimirPag = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtValorPago = new javax.swing.JTextField();
        btnLimparDados = new javax.swing.JButton();
        lblData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Mcoffe");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cliente");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Total R$");

        txtClientePag.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtClientePag.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblTroco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTroco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTabelaPag.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTabelaPag.setColumnSelectionAllowed(true);
        jTabelaPag.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTabelaPag);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Valor pago R$");

        btnCalcularPag.setText("Calcular");
        btnCalcularPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularPagActionPerformed(evt);
            }
        });

        btnImprimirPag.setText("Imprimir");
        btnImprimirPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirPagActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnPesquisar.setText("pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("troco");

        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtValorPago.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnLimparDados.setText("Limpar dados");
        btnLimparDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtClientePag, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPesquisar))
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnImprimirPag)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnCalcularPag)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLimparDados)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(txtValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClientePag, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularPag)
                    .addComponent(btnLimparDados, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnImprimirPag)
                        .addComponent(txtValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVoltar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblData.setText("Jandira 24/03/2016");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularPagActionPerformed
        // TODO add your handling code here: 
        if(!(txtClientePag.getText().isEmpty())){
            if(!(txtValorPago.getText().matches("([0-9]*)([.]?)([0-9]{0,2})")) || lblTotal.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Valor pago ou total invalido!");
            }else{
                try{
                    float x = Float.parseFloat(lblTotal.getText());
                    float y = Float.parseFloat(txtValorPago.getText());
                    if(y < x){            
                        x = x-y;
                        lblTroco.setText("R$ 0.00");                    
                    }else{
                        x = y-x;
                        lblTroco.setText("R$ "+String.format("%.2f", x));
                        x = 0;
                    }
                    String sql;
                    if(tipo == COMANDA)
                        sql = "UPDATE comanda SET lpre = "+x+" WHERE id = "+id+";";
                    else
                        sql = "UPDATE cliente SET cpre = "+x+" WHERE id = "+id+";";
                    cs.executeUpdate(sql);
                }catch(Exception e){
                    System.out.println(e);
                }
            }
        }
        btnPesquisarActionPerformed(evt);
    }//GEN-LAST:event_btnCalcularPagActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        PaginaInicial.pagInc.setVisible(true);
        Pagamento.this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        if(txtClientePag.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Preencha nome!");
            id = 0;
        }else{
            try {
                id = 0;
                if(txtClientePag.getText().matches("[0-9]{1,3}")){
                    cr = cs.executeQuery("select * from comanda where num like '%"+txtClientePag.getText()+"%';");
                    if(cr.first()){
                        txtClientePag.setText(cr.getString("num"));
                        lblTotal.setText(cr.getString("lpre"));
                        tipo = COMANDA;
                        id = cr.getInt("id");
                        preencherJTabela("SELECT * FROM venCom where idCom = '"+id+"';");
                    }
                }else{
                    cr = cs.executeQuery("select * from cliente where nome like '%"+txtClientePag.getText()+"%';");
                    if(cr.first()){
                        txtClientePag.setText(cr.getString("nome"));
                        lblTotal.setText(cr.getString("cpre"));
                        tipo = CLIENTE;
                        id = cr.getInt("id");
                        preencherJTabela("SELECT * FROM venCli where idCli = '"+id+"';");
                    }
                }
            } catch (Exception e) {}
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnImprimirPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirPagActionPerformed
        /* TODO add your handling code here:
        if(!"".equals(txtClientePag.getText())){
        try{
        jTabelaPag.print();
        }catch(Exception e){}
        btnPesquisarActionPerformed(evt);
        }    
        btnPesquisarActionPerformed(evt);//*/
    }//GEN-LAST:event_btnImprimirPagActionPerformed

    private void btnLimparDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparDadosActionPerformed
        // TODO add your handling code here:
        if(id != 0){
            try{
                if(tipo == CLIENTE)
                    cs.executeUpdate("DELETE FROM venda WHERE idCli = '"+id+"';");
                else if(tipo == COMANDA)
                    cs.executeUpdate("DELETE FROM venda WHERE idCom = '"+id+"';");
                JOptionPane.showMessageDialog(rootPane, "Dados limpos com sucesso!");
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Erro ao limpar dados!");
            }
        }    
        btnPesquisarActionPerformed(evt);
        //*/
    }//GEN-LAST:event_btnLimparDadosActionPerformed

    public void apagar(int r){
        if(r==0){
            // Apagar débitos dos clientes/comandas
        }
    }
    
    public void preencherJTabela(String SQL){
        //  "select * from clienteg"
        ArrayList dados = new ArrayList();
        
        String colunas[] = new String[]{"Descrição do produto","Data da compra","Preço"};
        if(!SQL.isEmpty()){
            try{
                cr = cs.executeQuery(SQL);
                cr.first();
                do{
                   dados.add(new Object[]{cr.getString("pro"),cr.getString("dat"),cr.getFloat("pre")});               
                }while(cr.next());      
            }catch(Exception e){
            }
        }
        JTabela tabela = new JTabela(dados, colunas);
        jTabelaPag.setModel(tabela);
        jTabelaPag.getColumnModel().getColumn(0).setPreferredWidth(170);
        jTabelaPag.getColumnModel().getColumn(0).setResizable(false);
        jTabelaPag.getColumnModel().getColumn(1).setPreferredWidth(127);
        jTabelaPag.getColumnModel().getColumn(1).setResizable(false);
        jTabelaPag.getColumnModel().getColumn(2).setPreferredWidth(65);
        jTabelaPag.getColumnModel().getColumn(2).setResizable(false);
        jTabelaPag.getTableHeader().setReorderingAllowed(false);
        jTabelaPag.setAutoResizeMode(jTabelaPag.AUTO_RESIZE_OFF);
        jTabelaPag.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //*/
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularPag;
    private javax.swing.JButton btnImprimirPag;
    private javax.swing.JButton btnLimparDados;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabelaPag;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JTextField txtClientePag;
    private javax.swing.JTextField txtValorPago;
    // End of variables declaration//GEN-END:variables
}
