package interfaces;

import static ferramentas.Conexao.*;
import java.util.Calendar;

/**
 *
 * @author AndersonCS
 */
public class PaginaInicial extends javax.swing.JFrame {

    /**
     * Creates new form PaginaInicial
     */
    static public PaginaInicial pagInc;
    public PaginaInicial() {
        initComponents();
        conexao();
        pagInc = this;
        Calendar d = Calendar.getInstance();
        String e = String.valueOf(d.get(Calendar.MONTH) + 1);
        if(e.length()==1){
           e="0"+e;           
        }
        lblData.setText("Jandira "+d.get(Calendar.DATE)+" / "+e+" / "+d.get(Calendar.YEAR));
    }  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCaixa = new javax.swing.JButton();
        btPagamentos = new javax.swing.JButton();
        btCadastrosComandas = new javax.swing.JButton();
        btEncerrar = new javax.swing.JButton();
        btCadastrosClientes = new javax.swing.JButton();
        btEstoque = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btCaixa.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btCaixa.setForeground(new java.awt.Color(0, 51, 255));
        btCaixa.setText("Caixa");
        btCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCaixaActionPerformed(evt);
            }
        });

        btPagamentos.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btPagamentos.setForeground(new java.awt.Color(0, 51, 255));
        btPagamentos.setText("Pagamentos");
        btPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPagamentosActionPerformed(evt);
            }
        });

        btCadastrosComandas.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btCadastrosComandas.setForeground(new java.awt.Color(0, 51, 255));
        btCadastrosComandas.setText("Cadastro de Comandas");
        btCadastrosComandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrosComandasActionPerformed(evt);
            }
        });

        btEncerrar.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btEncerrar.setForeground(new java.awt.Color(0, 51, 255));
        btEncerrar.setText("Encerrar");
        btEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEncerrarActionPerformed(evt);
            }
        });

        btCadastrosClientes.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btCadastrosClientes.setForeground(new java.awt.Color(0, 51, 255));
        btCadastrosClientes.setText("Cadastro de Clientes");
        btCadastrosClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrosClientesActionPerformed(evt);
            }
        });

        btEstoque.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btEstoque.setForeground(new java.awt.Color(0, 51, 255));
        btEstoque.setText("Estoque");
        btEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEstoqueActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mcoffe");

        lblData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblData.setForeground(new java.awt.Color(255, 0, 51));
        lblData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btPagamentos, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(btEncerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(btEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCadastrosComandas, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCadastrosClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCaixa)
                .addGap(20, 20, 20)
                .addComponent(btPagamentos)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrosComandas)
                    .addComponent(btCadastrosClientes))
                .addGap(18, 18, 18)
                .addComponent(btEstoque)
                .addGap(18, 18, 18)
                .addComponent(btEncerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCaixaActionPerformed
        // TODO add your handling code here:
        new Caixa().setVisible(true);
        pagInc.dispose();
    }//GEN-LAST:event_btCaixaActionPerformed

    private void btPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPagamentosActionPerformed
        // TODO add your handling code here:
        new Pagamento().setVisible(true);
        pagInc.dispose();
    }//GEN-LAST:event_btPagamentosActionPerformed

    private void btCadastrosComandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrosComandasActionPerformed
        // TODO add your handling code here:
        new CadastrosComanda().setVisible(true);
        pagInc.dispose();        
    }//GEN-LAST:event_btCadastrosComandasActionPerformed

    private void btEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEncerrarActionPerformed
        // TODO add your handling code here:
        pagInc.dispose();
        disconexao();
    }//GEN-LAST:event_btEncerrarActionPerformed

    private void btCadastrosClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrosClientesActionPerformed
        // TODO add your handling code here:        
        new CadastrosClientes().setVisible(true);
        pagInc.dispose();
    }//GEN-LAST:event_btCadastrosClientesActionPerformed

    private void btEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEstoqueActionPerformed
        // TODO add your handling code here:
        new Estoque().setVisible(true);
        pagInc.dispose();
    }//GEN-LAST:event_btEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrosClientes;
    private javax.swing.JButton btCadastrosComandas;
    private javax.swing.JButton btCaixa;
    private javax.swing.JButton btEncerrar;
    private javax.swing.JButton btEstoque;
    private javax.swing.JButton btPagamentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblData;
    // End of variables declaration//GEN-END:variables
}
