/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ControleCaixa;
import controle.Data;
import javax.swing.ListSelectionModel;
import modelo.Cliente;
import modelo.Comanda;
import modelo.Estoque;
import modelo.Vendas;

/**
 *
 * @author acsgs
 */
public class Caixa extends javax.swing.JFrame {
    int clicom=1,outro,com=1,cli=1,out=1,SQL;
    String outro1="Outro";
    Comanda comanda = new Comanda();
    Cliente cliente = new Cliente();
    Estoque estoque = new Estoque();
    Vendas vendas = new Vendas();
    ControleCaixa concai = new ControleCaixa();
    /**
     * Creates new form Caixa
     */
    public Caixa() {
        initComponents();
        Data.data();
        lblData.setText(Data.data);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCaixa = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnPesquisarPro = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnConfirmarcom = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtValorpag = new javax.swing.JTextField();
        btnConfirmarpag = new javax.swing.JButton();
        lblTroco = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnCliente = new javax.swing.JToggleButton();
        btnComanda = new javax.swing.JToggleButton();
        btnPesquisarcli = new javax.swing.JButton();
        txtProduto = new javax.swing.JTextField();
        lblCP = new javax.swing.JLabel();
        txtValorPro = new javax.swing.JTextField();
        btnOutro = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Caixa");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Caixa");
        jLabel1.setToolTipText("");

        lblData.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblData.setName(""); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CPF/CNJP");

        txtCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCliente.setEnabled(false);
        txtCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtClienteMouseClicked(evt);
            }
        });

        tabelaCaixa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaCaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelaCaixa.setOpaque(false);
        tabelaCaixa.setShowHorizontalLines(false);
        tabelaCaixa.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tabelaCaixa);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Total");

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Produto");

        btnPesquisarPro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPesquisarPro.setText("Pesquisar");
        btnPesquisarPro.setEnabled(false);
        btnPesquisarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Valor do produto");

        btnConfirmarcom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConfirmarcom.setText("Confirmar compra");
        btnConfirmarcom.setEnabled(false);
        btnConfirmarcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarcomActionPerformed(evt);
            }
        });

        btnImprimir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Valor pago");

        txtValorpag.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtValorpag.setEnabled(false);
        txtValorpag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtValorpagMouseClicked(evt);
            }
        });

        btnConfirmarpag.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConfirmarpag.setText("Confirmar pagamento");
        btnConfirmarpag.setEnabled(false);
        btnConfirmarpag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarpagActionPerformed(evt);
            }
        });

        lblTroco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTroco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Troco");

        btnCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCliente.setText("Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnComanda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnComanda.setText("Comanda");
        btnComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComandaActionPerformed(evt);
            }
        });

        btnPesquisarcli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPesquisarcli.setText("Pesquisar");
        btnPesquisarcli.setEnabled(false);
        btnPesquisarcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarcliActionPerformed(evt);
            }
        });

        txtProduto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtProduto.setEnabled(false);
        txtProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtProdutoMouseClicked(evt);
            }
        });

        lblCP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txtValorPro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtValorPro.setEnabled(false);

        btnOutro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOutro.setText("Outro");
        btnOutro.setEnabled(false);
        btnOutro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnConfirmarcom, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                            .addComponent(txtValorpag))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnConfirmarpag))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnPesquisarPro)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnOutro)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtValorPro)
                                    .addComponent(lblTroco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnPesquisarcli))))
                            .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisarcli, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConfirmarcom)
                            .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorpag, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConfirmarpag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtValorPro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(btnOutro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(78, 78, 78)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(873, 670));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarcliActionPerformed
        // TODO add your handling code here:
        short txt=1;
        String cp="";
        if(clicom==1){
            cliente.setNocli(txtCliente.getText());
            concai.pesquisarcli(cliente);
            txtCliente.setText(cliente.getNocli());
            lblCP.setText(cliente.getCpcli());            
            btnPesquisarPro.setEnabled(false);
            SQL = cliente.getIdcli();
        }else{
            try{
                comanda.setNucom(txtCliente.getText());
                concai.pesquisarcom(comanda);                
                txtCliente.setText(String.valueOf(comanda.getNucom()));
                lblCP.setText("-");                
                btnPesquisarPro.setEnabled(false);
            }catch(Exception e){
                clicom=2;
                txtCliente.setText("Preencha corretamente");
                txtProduto.setEnabled(false);
                lblCP.setText(null);
                btnOutro.setEnabled(false);
                btnPesquisarPro.setEnabled(false);
            }                        
        } 
        if(lblCP.getText()!=null){
            btnImprimir.setEnabled(true);
            txtProduto.setEnabled(true);
            btnOutro.setEnabled(true);
            txtValorpag.setEnabled(true);            
            tabelaCaixaPrencher();
        }
    }//GEN-LAST:event_btnPesquisarcliActionPerformed

    private void txtClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtClienteMouseClicked
        // TODO add your handling code here:
        txtCliente.selectAll();
    }//GEN-LAST:event_txtClienteMouseClicked

    private void txtProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProdutoMouseClicked
        // TODO add your handling code here:
        txtProduto.selectAll();
        btnPesquisarPro.setEnabled(true);
    }//GEN-LAST:event_txtProdutoMouseClicked

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:        
        if(cli==1){
            btnComanda.setSelected(false);
            clicom=1;
            btnPesquisarcli.setEnabled(true);
            txtCliente.setEnabled(true);
            lblCP.setText(null);
            txtProduto.setEnabled(false);
            btnOutro.setEnabled(false);
            btnPesquisarPro.setEnabled(false);
            btnImprimir.setEnabled(false);
            txtValorpag.setEnabled(false);
            btnConfirmarpag.setEnabled(false);
            cli=2;
            com=1;           
        }else{
            btnPesquisarcli.setEnabled(false);
            txtCliente.setEnabled(false);
            lblCP.setText(null);
            txtProduto.setEnabled(false);
            btnOutro.setEnabled(false);
            btnPesquisarPro.setEnabled(false);
            btnImprimir.setEnabled(false);
            txtValorpag.setEnabled(false);
            btnConfirmarpag.setEnabled(false);
            cli=1;
            com=1;
        }
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComandaActionPerformed
        // TODO add your handling code here:
        if(com==1){
            btnCliente.setSelected(false);
            clicom=2;
            btnPesquisarcli.setEnabled(true);
            txtCliente.setEnabled(true);
            lblCP.setText(null);
            txtProduto.setEnabled(false);
            btnOutro.setEnabled(false);
            btnPesquisarPro.setEnabled(false);
            btnImprimir.setEnabled(false);
            txtValorpag.setEnabled(false);
            btnConfirmarpag.setEnabled(false);
            com=2;
            cli=1;
        }else{
            btnPesquisarcli.setEnabled(false);
            txtCliente.setEnabled(false);
            lblCP.setText(null);
            txtProduto.setEnabled(false);
            btnOutro.setEnabled(false);
            btnPesquisarPro.setEnabled(false);
            btnImprimir.setEnabled(false);
            txtValorpag.setEnabled(false);
            btnConfirmarpag.setEnabled(false);
            com=1;
            cli=1;
        }
    }//GEN-LAST:event_btnComandaActionPerformed

    private void btnOutroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutroActionPerformed
        // TODO add your handling code here:
        if(out==1){
            txtValorPro.setEnabled(true);
            btnConfirmarcom.setEnabled(true);
            txtProduto.setEnabled(false);
            btnPesquisarPro.setEnabled(false);
            outro=1;
            out=2;
        }else{
            txtValorPro.setEnabled(false);
            btnConfirmarcom.setEnabled(false);
            txtProduto.setEnabled(true);
            btnPesquisarPro.setEnabled(false);
            outro=0;
            out=1;
        }
    }//GEN-LAST:event_btnOutroActionPerformed

    private void txtValorpagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValorpagMouseClicked
        // TODO add your handling code here:
        btnConfirmarpag.setEnabled(true);    
    }//GEN-LAST:event_txtValorpagMouseClicked

    private void btnPesquisarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProActionPerformed
        // TODO add your handling code here:
        if("".equals(txtProduto.getText())){
            txtProduto.setText("Vazio");
        }else{
            estoque.setNopro(txtProduto.getText());
            concai.pesquisarPro(estoque);
            txtProduto.setText(estoque.getNopro());
            txtValorPro.setText(String.valueOf(estoque.getPrpro()));
            txtValorPro.setEnabled(false);
            btnConfirmarcom.setEnabled(true);
        }
    }//GEN-LAST:event_btnPesquisarProActionPerformed

    private void btnConfirmarcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarcomActionPerformed
        // TODO add your handling code here:
        int conf;
        if(clicom==1){
            if(outro==1){
                conf = 1;
                vendas.setPrven(Float.parseFloat(txtValorPro.getText()));
                concai.confirmarCompraCli(vendas,estoque,cliente,conf);
                btnPesquisarcliActionPerformed(evt);
                btnPesquisarPro.setEnabled(false);
                txtProduto.setEnabled(false);
            }else{
                conf = 2;
                concai.confirmarCompraCli(vendas,estoque,cliente,conf);
                btnPesquisarcliActionPerformed(evt);
            }
        }else{
            if(outro==1){
                conf = 1;
                vendas.setPrven(Float.parseFloat(txtValorPro.getText()));
                concai.confirmarCompraCom(vendas,estoque,comanda,conf);
                btnPesquisarcliActionPerformed(evt);
                btnPesquisarPro.setEnabled(false);
                txtProduto.setEnabled(false);
            }else{
                conf = 2;
                concai.confirmarCompraCom(vendas,estoque,comanda,conf);
                btnPesquisarcliActionPerformed(evt);
            }
        }
    }//GEN-LAST:event_btnConfirmarcomActionPerformed

    private void btnConfirmarpagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarpagActionPerformed
        // TODO add your handling code here:
        if("".equals(txtValorpag.getText())){
            txtValorpag.setText("Vazio");
        }else{
            float valorpag = Float.parseFloat(txtValorpag.getText());
            concai.confirmarPagamento(valorpag);
        }
    }//GEN-LAST:event_btnConfirmarpagActionPerformed

    private void tabelaCaixaPrencher(){
        if(clicom==1){
        concai.preencherTabelaCaixaCli(SQL);
        tabelaCaixa.setModel(concai.tabela);
        tabelaCaixa.getColumnModel().getColumn(0).setPreferredWidth(501);
        tabelaCaixa.getColumnModel().getColumn(0).setResizable(true);
        tabelaCaixa.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabelaCaixa.getColumnModel().getColumn(1).setResizable(true);
        tabelaCaixa.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabelaCaixa.getColumnModel().getColumn(2).setResizable(true);
        tabelaCaixa.getTableHeader().setReorderingAllowed(false);
        tabelaCaixa.setAutoResizeMode(tabelaCaixa.AUTO_RESIZE_OFF);
        tabelaCaixa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        String tot=String.format("%.2f", concai.total);
        lblTotal.setText(" R$ "+tot);
        }else if(clicom==2){
            concai.preencherTabelaCaixaCom(comanda);
            tabelaCaixa.setModel(concai.tabela);
            tabelaCaixa.getColumnModel().getColumn(0).setPreferredWidth(501);
            tabelaCaixa.getColumnModel().getColumn(0).setResizable(true);
            tabelaCaixa.getColumnModel().getColumn(1).setPreferredWidth(200);
            tabelaCaixa.getColumnModel().getColumn(1).setResizable(true);
            tabelaCaixa.getColumnModel().getColumn(2).setPreferredWidth(100);
            tabelaCaixa.getColumnModel().getColumn(2).setResizable(true);
            tabelaCaixa.getTableHeader().setReorderingAllowed(false);
            tabelaCaixa.setAutoResizeMode(tabelaCaixa.AUTO_RESIZE_OFF);
            tabelaCaixa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            String tot=String.format("%.2f", concai.total);
            lblTotal.setText(" R$ "+tot);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCliente;
    private javax.swing.JToggleButton btnComanda;
    private javax.swing.JButton btnConfirmarcom;
    private javax.swing.JButton btnConfirmarpag;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JToggleButton btnOutro;
    private javax.swing.JButton btnPesquisarPro;
    private javax.swing.JButton btnPesquisarcli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCP;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JTable tabelaCaixa;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtValorPro;
    private javax.swing.JTextField txtValorpag;
    // End of variables declaration//GEN-END:variables
}
